---
- name: install php
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-gd
    - php5-mysql
    - php5-curl
    - php5-mcrypt
- name: Enable MCrypt
  command: php5enmod mcrypt
