---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    database: portland_dsa
  roles:
    - { role: general }
    - { role: apache, document_root: /vagrant }
    - { role: php }
    - { role: mysql, root_db_password: root }
  tasks:
    - name: add WP database
      mysql_db: name={{ database }} state=present
