---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    database: wordpress_dev
  roles:
    - { role: general }
    - { role: apache, document_root: /vagrant }
    - { role: php }
    - { role: mysql, root_db_password: root }
  tasks:
    - name: add Craft database
      mysql_db: name={{ database }} state=present
